name: Run FastAPI Tests (PostgreSQL)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U testuser -d testdb"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set Test Database Environment Variables
        run: |
          echo "RUN_MODE=test" >> $GITHUB_ENV
          echo "DB_HOST=localhost" >> $GITHUB_ENV
          echo "DB_PORT=5432" >> $GITHUB_ENV
          echo "DB_NAME=testdb" >> $GITHUB_ENV
          echo "DB_USER=testuser" >> $GITHUB_ENV
          echo "DB_PASS=testpass" >> $GITHUB_ENV
          echo "JWT_SECRET=testsecret" >> $GITHUB_ENV
          echo "JWT_ALGORITHM=HS256" >> $GITHUB_ENV

      - name: Wait for PostgreSQL to be Ready
        run: |
          for i in {1..10}; do
            pg_isready -h localhost -p 5432 -U testuser && break
            echo "Waiting for PostgreSQL..."
            sleep 3
          done

      - name: Initialize Database Schema
        run: |
          source venv/bin/activate
          python -c "from main import create_db_and_tables; create_db_and_tables()"

      - name: Run FastAPI Tests
        run: |
          source venv/bin/activate
          pytest test/
